import { generateQueryString, openWithBrowser } from '../../utils';
import {
	GOOGLE_OAUTH2_AUTHORIZE_ENDPOINT,
	GOOGLE_OAUTH2_TOKEN_ENDPOINT,
	GOOGLE_OAUTH2_VALIDATE_TOKEN_ENDPOINT,
} from '../../consts';
import { IBrand } from '../../types';
import { getGlobalI18n } from '../../i18n/i18n';
import { IOauth2ClientCredentials } from '../../plugin-settings';
import { IObsidianRequest } from '../request/abstract-request-client';
import { AbstractRequestClientWithConstructor } from '../request/request-client';
import { EnumHttpMethod } from '../request/http-post';

/**
 * OAuth2 Token 原型（僅包含最基本的 token 資訊）
 * OAuth2 Token prototype (minimal token info only)
 *
 * 來自 Google OAuth2 token 端點的原始回應中，最基本的必要欄位。
 * 完整的 token 回應應使用 IOAuth2Token。
 * Minimal required fields from a Google OAuth2 token endpoint response.
 * For the full token response, use IOAuth2Token instead.
 */
export type IOAuth2TokenProto = {
	/** 存取權杖 / Access token */
	accessToken: string;
	/** Token 類型（通常為 "Bearer"）/ Token type (usually "Bearer") */
	tokenType: string;
};

/**
 * OAuth2 Token（完整，對應 Google token 端點回應）
 * OAuth2 Token (full, maps to Google token endpoint response)
 *
 * 對應 Google OAuth2 token endpoint 回傳的 JSON 結構。
 * Maps to the JSON structure returned by the Google OAuth2 token endpoint.
 */
export type IOAuth2Token = IOAuth2TokenProto & {
	/** 有效期限（秒）/ Expiration (seconds) */
	expiresIn: number;
	/** 更新權杖 / Refresh token */
	refreshToken: string;
	/** 授權範圍 / OAuth2 scope */
	scope: string;
};

/**
 * 內部 OAuth2 Token（含到期時間戳）
 * Internal OAuth2 Token (with absolute expiry timestamp)
 *
 * 將 `expiresIn`（相對秒數）轉換為 `expiresAt`（絕對時間戳）以便快速比對。
 * 使用 `isFreshInternalOAuth2Token()` type guard 判斷是否仍有效。
 * Converts `expiresIn` (relative seconds) to `expiresAt` (absolute timestamp) for quick comparison.
 * Use `isFreshInternalOAuth2Token()` type guard to check if still valid.
 */
export type IInternalOAuth2Token = IOAuth2Token & {
	/**
	 * 到期絕對時間戳（毫秒）
	 * Absolute expiration timestamp (milliseconds)
	 *
	 * 計算方式：requestTime + (expiresIn - 60) * 1000
	 * 減 60 秒作為緩衝，避免 token 在邊界時間失效。
	 * Calculated as: requestTime + (expiresIn - 60) * 1000
	 * 60-second buffer to prevent token expiry at boundary time.
	 */
	expiresAt: number;
};

/**
 * 新鮮（有效）的內部 OAuth2 Token
 * Fresh (valid) Internal OAuth2 Token
 *
 * 使用 TypeScript Branded Type（幻影型別）區分已驗證有效與未驗證的 token。
 * 只有通過 `isFreshInternalOAuth2Token()` 檢查的 token 才能賦予此型別。
 * Uses TypeScript branded type (phantom type) to distinguish
 * verified-valid tokens from unverified ones.
 * Only tokens passing `isFreshInternalOAuth2Token()` get this type.
 */
export type IFreshInternalOAuth2Token = IBrand<IInternalOAuth2Token, 'IFreshInternalOAuth2Token'>;

/**
 * Type Guard：檢查 IInternalOAuth2Token 是否仍有效
 * Type guard: check if IInternalOAuth2Token is still fresh
 *
 * 比較 expiresAt 與當前時間戳。
 * 通過此檢查的 token 會被 TypeScript 縮窄為 IFreshInternalOAuth2Token。
 * Compares expiresAt against the current timestamp.
 * Passing this check narrows the type to IFreshInternalOAuth2Token.
 *
 * @param token - 待檢查的內部 token / Internal token to check
 * @returns token 是否仍有效 / Whether the token is still fresh
 */
const isFreshInternalOAuth2Token = (
	token: IInternalOAuth2Token,
): token is IFreshInternalOAuth2Token =>
{
	return token.expiresAt > Date.now();
};

/**
 * 取得授權碼所需參數
 * Parameters for obtaining the authorization code
 *
 * 對應 Google OAuth2 authorize endpoint 的查詢字串參數。
 * Maps to the query string parameters of the Google OAuth2 authorize endpoint.
 */
export type IGetAuthorizeCodeParams = {
	/** 授權完成後重新導向的 URI / Redirect URI after authorization */
	redirectUri: string;
	/**
	 * OAuth2 授權範圍列表
	 * OAuth2 scope list
	 *
	 * 預設為 BLOGGER_OAUTH2_SCOPE，但可傳入多個 scope。
	 * Defaults to BLOGGER_OAUTH2_SCOPE, but multiple scopes may be passed.
	 */
	scope?: string[];
	/** 目標部落格 ID（選擇性，用於提前指定） / Target blog ID (optional) */
	blog?: string;
	/**
	 * PKCE code verifier（用於 S256 挑戰）
	 * PKCE code verifier (for S256 challenge)
	 *
	 * 由 generateCodeVerifier() 產生，後續用於 getToken() 交換授權碼。
	 * Generated by generateCodeVerifier(), later used in getToken() to exchange the authorization code.
	 */
	codeVerifier: string;
	/**
	 * 自訂狀態值（用於 CSRF 防護）
	 * Custom state value (for CSRF protection)
	 *
	 * 可選，用於防止跨站請求偽造。
	 * Optional, used to prevent cross-site request forgery.
	 */
	state?: string;
};

/**
 * 交換授權碼取得 Token 所需參數
 * Parameters for exchanging authorization code for tokens
 *
 * 對應 Google OAuth2 token endpoint 的 POST 主體。
 * Maps to the POST body of the Google OAuth2 token endpoint.
 */
export type IGetTokenParams = {
	/** 來自授權流程的授權碼 / Authorization code from the auth flow */
	code: string;
	/** 與授權請求一致的重新導向 URI / Redirect URI matching the auth request */
	redirectUri: string;
	/** 與授權請求一致的 PKCE code verifier / PKCE code verifier matching the auth request */
	codeVerifier: string;
};

/**
 * 更新 Token 所需參數
 * Parameters for refreshing an OAuth2 token
 *
 * 對應 Google OAuth2 token endpoint 的 refresh_token grant 請求主體。
 * Maps to the refresh_token grant request body of the Google OAuth2 token endpoint.
 */
export type IRefreshTokenParams = {
	/** Google OAuth2 客戶端 ID / Google OAuth2 client ID */
	client_id: string;
	/** Google OAuth2 客戶端密鑰 / Google OAuth2 client secret */
	client_secret: string;
	/** 更新權杖（來自初次授權的 refresh_token）/ Refresh token from initial authorization */
	refresh_token: string;
};

/**
 * 驗證 Token 所需參數
 * Parameters for validating an OAuth2 token
 *
 * 對應 Google OAuth2 tokeninfo endpoint 的查詢參數。
 * Maps to the query parameters of the Google OAuth2 tokeninfo endpoint.
 */
export type IValidateTokenParams = {
	/** 待驗證的 access token / Access token to validate */
	token: string;
};

/**
 * OAuth2 客戶端建構選項
 * OAuth2 client constructor options
 *
 * 包含 Google OAuth2 所需的端點 URL 與客戶端憑證。
 * Contains the required endpoints and client credentials for Google OAuth2.
 */
export type IOAuth2Options = {
	/** Google OAuth2 客戶端 ID / Google OAuth2 client ID */
	clientId: string;
	/** Google OAuth2 客戶端密鑰 / Google OAuth2 client secret */
	clientSecret: string;
	/**
	 * Token 端點 URL / Token endpoint URL
	 *
	 * 通常為 GOOGLE_OAUTH2_TOKEN_ENDPOINT（由 getGoogleOAuth2Client() 自動設定）。
	 * Usually GOOGLE_OAUTH2_TOKEN_ENDPOINT (set automatically by getGoogleOAuth2Client()).
	 */
	tokenEndpoint: string;
	/**
	 * 授權端點 URL / Authorize endpoint URL
	 *
	 * 通常為 GOOGLE_OAUTH2_AUTHORIZE_ENDPOINT（由 getGoogleOAuth2Client() 自動設定）。
	 * Usually GOOGLE_OAUTH2_AUTHORIZE_ENDPOINT (set automatically by getGoogleOAuth2Client()).
	 */
	authorizeEndpoint: string;
	/**
	 * Token 驗證端點 URL / Token validation endpoint URL
	 *
	 * 通常為 GOOGLE_OAUTH2_VALIDATE_TOKEN_ENDPOINT（由 getGoogleOAuth2Client() 自動設定）。
	 * Usually GOOGLE_OAUTH2_VALIDATE_TOKEN_ENDPOINT (set automatically by getGoogleOAuth2Client()).
	 */
	validateTokenEndpoint: string;
};

/**
 * 建立 Google OAuth2 客戶端實例
 * Create a Google OAuth2 client instance
 *
 * 從 plugin settings 讀取 OAuth2 客戶端憑證，
 * 並自動填入 Google OAuth2 端點 URL。
 * Reads OAuth2 client credentials from plugin settings
 * and automatically fills in the Google OAuth2 endpoint URLs.
 *
 * @param oAuth2ClientCredentials - 來自 plugin settings 的 OAuth2 客戶端憑證 / OAuth2 client credentials from settings
 * @returns 已設定的 OAuth2Client 實例 / Configured OAuth2Client instance
 */
export const getGoogleOAuth2Client = (
	oAuth2ClientCredentials: IOauth2ClientCredentials,
): OAuth2Client =>
{
	return new OAuth2Client({
		...oAuth2ClientCredentials,
		tokenEndpoint: GOOGLE_OAUTH2_TOKEN_ENDPOINT,
		authorizeEndpoint: GOOGLE_OAUTH2_AUTHORIZE_ENDPOINT,
		validateTokenEndpoint: GOOGLE_OAUTH2_VALIDATE_TOKEN_ENDPOINT,
	});
};

/**
 * OAuth2 客戶端類別
 * OAuth2 client class
 *
 * 封裝 Google OAuth2 授權流程，支援：
 * Encapsulates the Google OAuth2 authorization flow, supporting:
 *
 * 1. PKCE（Proof Key for Code Exchange）授權碼流程 / PKCE authorization code flow
 *    - getAuthorizeCode() → 瀏覽器開啟 Google 授權頁面
 *    - getToken() → 交換授權碼為 access token + refresh token
 *    - generateCodeVerifier() → 產生 PKCE code verifier
 *
 * 2. Token 更新 / Token refresh
 *    - refreshToken() → 使用 refresh token 取得新 access token
 *    - ensureFreshToken() → 自動判斷是否需要 refresh
 *
 * 3. Token 驗證 / Token validation
 *    - validateToken() → 向 Google 確認 token 是否有效
 *
 * @see https://developers.google.com/identity/protocols/oauth2/native-app Google OAuth2 for native apps
 * @see https://developers.google.com/identity/protocols/oauth2/web-server Google OAuth2 for web server apps
 */
export class OAuth2Client extends AbstractRequestClientWithConstructor
{
	constructor(protected readonly options: IOAuth2Options, obsidianRequest?: IObsidianRequest)
	{
		super(obsidianRequest);
	}

	/**
	 * 處理 Token 請求與解析回應
	 * Handle Token request and parse response
	 *
	 * @param body - 請求主體物件 / Request body object
	 * @param fallbackRefreshToken - 退回使用的 refresh token（若回應中未包含）/ Fallback refresh token (if not in response)
	 * @returns 新鮮的內部 Token / Fresh internal token
	 */
	protected async _requestAndParseToken(
		body: Record<string, string>,
		fallbackRefreshToken?: string,
	): Promise<IFreshInternalOAuth2Token>
	{
		const requestTime = Date.now();
		const response = await this.requestUrl({
			url: this.options.tokenEndpoint,
			method: EnumHttpMethod.POST,
			headers: {
				'Content-Type': 'application/x-www-form-urlencoded',
				'User-Agent': 'obsidian.md',
			},
			body: generateQueryString(body),
		});
		const resp = response.json;
		const expiresIn = Number(resp.expires_in);
		/**
		 * 計算絕對到期時間（減 60 秒緩衝）
		 * Calculate absolute expiry (minus 60-second buffer)
		 *
		 * expiresIn 為 Google 回傳的相對秒數。
		 * 減 60 秒確保在 token 真正到期前觸發 refresh，避免邊界狀況。
		 * expiresIn is the relative seconds from Google.
		 * 60-second buffer ensures refresh triggers before actual expiry, preventing edge cases.
		 */
		const expiresAt = requestTime + Math.max(0, expiresIn - 60) * 1000;
		const res = {
			accessToken: resp.access_token,
			tokenType: resp.token_type,
			expiresIn,
			expiresAt,
			/**
			 * Google 有時不會回傳新的 refresh_token。
			 * 此時保留舊的 fallbackRefreshToken。
			 * Google sometimes omits refresh_token in the response.
			 * In that case, retain the old fallbackRefreshToken.
			 */
			refreshToken: resp.refresh_token ?? fallbackRefreshToken,
			scope: resp.scope,
		};
		if (!isFreshInternalOAuth2Token(res as IInternalOAuth2Token))
		{
			throw new Error(getGlobalI18n().t('error_invalidGoogleToken'));
		}
		return res as IFreshInternalOAuth2Token;
	}

	/**
	 * 取得授權碼（開啟瀏覽器前往 Google 授權頁面）
	 * Get authorization code (opens browser to Google authorization page)
	 *
	 * 使用 PKCE（S256）流程產生授權請求 URL，並以瀏覽器開啟。
	 * 使用者完成授權後，Google 會重新導向至 redirectUri 並附帶授權碼。
	 * Uses PKCE (S256) flow to generate the authorization request URL and opens it in a browser.
	 * After the user completes authorization, Google redirects to redirectUri with the authorization code.
	 *
	 * ⚠️ 不會等待使用者回應。呼叫端需自行實作授權碼接收機制
	 *    （桌面版透過 localhost server，網頁版透過 proxy）。
	 * ⚠️ Does NOT wait for user response. Callers must implement their own
	 *    authorization code receiver (desktop: localhost server, web: proxy).
	 *
	 * @param params - 授權請求參數 / Authorization request parameters
	 */
	getAuthorizeCode = async (params: IGetAuthorizeCodeParams): Promise<void> =>
	{
		const query: {
			client_id: string;
			response_type: 'code';
			redirect_uri: string;
			code_challenge_method?: 'plain' | 'S256';
			code_challenge?: string;
			blog?: string;
			scope?: string;
			state?: string;
			/**
			 * 強制要求 refresh token / Force refresh token request
			 *
			 * 預設 Google 只在首次授權時回傳 refresh_token。
			 * 設定 access_type=offline 與 prompt=consent 確保每次授權都取得新的 refresh_token。
			 * By default Google only returns refresh_token on first authorization.
			 * Setting access_type=offline with prompt=consent ensures a new refresh_token each time.
			 *
			 * @see https://stackoverflow.com/questions/10827920/not-receiving-google-oauth-refresh-token
			 */
			access_type: 'offline';
			prompt: 'consent';
		} = {
			client_id: this.options.clientId,
			response_type: 'code',
			redirect_uri: params.redirectUri,
			blog: params.blog,
			scope: undefined,
			state: params.state,
			access_type: 'offline',
			prompt: 'consent',
		};
		if (params.scope)
		{
			query.scope = params.scope.join(' ');
		}
		if (params.codeVerifier)
		{
			const codeChallenge = await getCodeChallenge(params.codeVerifier);
			query.code_challenge_method = codeChallenge?.[0];
			query.code_challenge = codeChallenge?.[1];
		}
		openWithBrowser(this.options.authorizeEndpoint, query);
	};

	/**
	 * 交換授權碼取得 Token
	 * Exchange authorization code for tokens
	 *
	 * 將使用者授權後取得的授權碼，透過 token endpoint 交換為
	 * access token（短期）與 refresh token（長期）。
	 * Exchanges the authorization code for an access token (short-lived)
	 * and a refresh token (long-lived) via the token endpoint.
	 *
	 * 使用 PKCE code verifier 確保只有原始請求者能完成交換。
	 * Uses PKCE code verifier to ensure only the original requester can complete the exchange.
	 *
	 * @param params - Token 交換參數（含授權碼與 code verifier）/ Token exchange parameters
	 * @returns 新鮮的內部 Token（通過新鮮度檢查）/ Fresh internal token (freshness validated)
	 * @throws 若回傳的 token 已過期（不應發生，但防禦性檢查）
	 * @throws If the returned token is already expired (defensive check, should not happen)
	 */
	getToken = async (params: IGetTokenParams): Promise<IFreshInternalOAuth2Token> =>
	{
		const body: {
			grant_type: 'authorization_code';
			client_id: string;
			client_secret: string;
			code: string;
			redirect_uri: string;
			code_verifier: string;
		} = {
			grant_type: 'authorization_code',
			client_id: this.options.clientId,
			client_secret: this.options.clientSecret,
			code: params.code,
			redirect_uri: params.redirectUri,
			code_verifier: params.codeVerifier,
		};

		return this._requestAndParseToken(body);
	};

	/**
	 * 更新 Token（使用 refresh token 取得新的 access token）
	 * Refresh token (use refresh token to get a new access token)
	 *
	 * 當 access token 過期時，使用 refresh token 向 Google 請求新的 access token。
	 * 如 Google 未回傳新的 refresh token，保留原有的 refresh token。
	 * When the access token expires, use the refresh token to request a new one from Google.
	 * If Google does not return a new refresh token, retain the existing one.
	 *
	 * @param params - 更新參數（含 client_id、client_secret、refresh_token）/ Refresh parameters
	 * @returns 新鮮的內部 Token / Fresh internal token
	 * @throws 若更新後 token 仍過期 / If the refreshed token is still expired
	 */
	refreshToken = async (params: IRefreshTokenParams): Promise<IFreshInternalOAuth2Token> =>
	{
		const body: {
			grant_type: 'refresh_token';
			client_id: string;
			client_secret: string;
			refresh_token: string;
		} = {
			grant_type: 'refresh_token',
			client_id: this.options.clientId,
			client_secret: this.options.clientSecret,
			refresh_token: params.refresh_token,
		};

		return this._requestAndParseToken(body, params.refresh_token);
	};

	/**
	 * 確保 Token 有效（必要時自動更新）
	 * Ensure token is fresh (auto-refresh if needed)
	 *
	 * 檢查 token 是否仍在有效期限內：
	 * - 若有效 → 直接回傳
	 * - 若過期 → 自動呼叫 refreshToken() 更新
	 *
	 * Checks whether the token is still valid:
	 * - If fresh → return as-is
	 * - If expired → auto-call refreshToken()
	 *
	 * 這是絕大多數呼叫端應使用的方法，無需手動檢查到期與否。
	 * This is the method most callers should use — no need to manually check expiry.
	 *
	 * @param token - 可能已過期的內部 Token / Potentially expired internal token
	 * @returns 新鮮有效的 Token / Fresh valid token
	 */
	ensureFreshToken = async (token: IInternalOAuth2Token): Promise<IFreshInternalOAuth2Token> =>
	{
		if (isFreshInternalOAuth2Token(token))
		{
			return token;
		}
		else
		{
			return this.refreshToken({
				client_id: this.options.clientId,
				client_secret: this.options.clientSecret,
				refresh_token: token.refreshToken,
			});
		}
	};

	/**
	 * 驗證 Token 是否有效
	 * Validate whether a token is still valid
	 *
	 * 向 Google 的 tokeninfo 端點發送 GET 請求確認 token 狀態。
	 * 若請求失敗（HTTP 錯誤），表示 token 已失效。
	 * Sends a GET request to Google's tokeninfo endpoint to verify token status.
	 * If the request fails (HTTP error), the token is invalid.
	 *
	 * @param params - 驗證參數（含 access token）/ Validation parameters (with access token)
	 */
	validateToken = async (params: IValidateTokenParams): Promise<void> =>
	{
		await this.requestUrl({
			url: `${this.options.validateTokenEndpoint}?access_token=${params.token}`,
			method: EnumHttpMethod.GET,
			headers: {
				'Content-Type': 'application/json',
				'User-Agent': 'obsidian.md',
			},
		});
	};
}

/**
 * 產生 PKCE Code Verifier
 * Generate PKCE Code Verifier
 *
 * 使用 crypto.getRandomValues() 產生 32 個隨機位元組，
 * 再以 base64url 編碼作為 code verifier。
 * Uses crypto.getRandomValues() to generate 32 random bytes,
 * then base64url-encodes them as the code verifier.
 *
 * 此值需同時用於 getAuthorizeCode()（作為 S256 挑戰的輸入）
 * 與 getToken()（驗證原始請求者身份）。
 * This value must be used both in getAuthorizeCode() (as input for S256 challenge)
 * and in getToken() (to verify the original requester's identity).
 *
 * @returns base64url 編碼的 code verifier / Base64url-encoded code verifier
 */
export const generateCodeVerifier = (): string =>
{
	const arr = new Uint8Array(32);
	crypto.getRandomValues(arr);
	return base64Url(arr);
};

/**
 * 計算 PKCE S256 Code Challenge
 * Compute PKCE S256 Code Challenge
 *
 * 使用 SHA-256 對 code verifier 進行雜湊，再以 base64url 編碼。
 * Hashes the code verifier with SHA-256, then base64url-encodes it.
 *
 * @param codeVerifier - 由 generateCodeVerifier() 產生的 verifier / Verifier from generateCodeVerifier()
 * @returns [方法, 挑戰值] / [method, challenge value] — ["S256", <base64url-hash>]
 */
const getCodeChallenge = async (codeVerifier: string): Promise<['plain' | 'S256', string]> =>
{
	return ['S256', base64Url(await crypto.subtle.digest('SHA-256', stringToBuffer(codeVerifier)))];
};

/**
 * 將字串轉換為 Uint8Array（用於 crypto.subtle.digest）
 * Convert string to Uint8Array (for crypto.subtle.digest)
 *
 * @param input - 輸入字串 / Input string
 * @returns Uint8Array（每個字元取低位元組）/ Uint8Array (lower byte of each character)
 */
const stringToBuffer = (input: string) =>
{
	const buf = new Uint8Array(input.length);
	for (let i = 0; i < input.length; i++)
	{
		buf[i] = input.charCodeAt(i) & 0xff;
	}
	return buf;
};

/**
 * Base64url 編碼（RFC 4648 §5）
 * Base64url encoding (RFC 4648 §5)
 *
 * 標準 Base64 的 URL-safe 變體，使用 `-` 取代 `+`、`_` 取代 `/`，
 * 並移除結尾的 `=` padding。
 * URL-safe variant of standard Base64: `-` instead of `+`, `_` instead of `/`,
 * and trailing `=` padding removed.
 *
 * 用於 PKCE code verifier 與 code challenge 的編碼。
 * Used for encoding PKCE code verifiers and code challenges.
 *
 * @param buf - 來源資料（ArrayBuffer 或 Uint8Array）/ Source data
 * @returns Base64url 編碼字串（無 padding）/ Base64url encoded string (no padding)
 */
const base64Url = (buf: ArrayBuffer | Uint8Array): string =>
{
	return btoa(String.fromCharCode(...new Uint8Array(buf)))
		.replace(/\+/g, '-')
		.replace(/\//g, '_')
		.replace(/=+$/, '');
};
